name: sync_tasks
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.3.0
  local_auth: ^2.3.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.7
  get_it: ^7.7.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.12
  mobx_codegen: ^2.0.0



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: NeueMontreal
      fonts:
        - asset: assets/fonts/neueMontreal/NeueMontreal-Bold.otf
        - asset: assets/fonts/neueMontreal/NeueMontreal-BoldItalic.otf
        - asset: assets/fonts/neueMontreal/NeueMontreal-Italic.otf
        - asset: assets/fonts/neueMontreal/NeueMontreal-Light.otf
        - asset: assets/fonts/neueMontreal/NeueMontreal-LightItalic.otf
        - asset: assets/fonts/neueMontreal/NeueMontreal-Medium.otf
        - asset: assets/fonts/neueMontreal/NeueMontreal-MediumItalic.otf
        - asset: assets/fonts/neueMontreal/NeueMontreal-Regular.otf
